

#get the translation table for a given phylum-family.
#if ambigious, 0 is returned, indicating it is safest to employ censored translation.
which_trans_table("Entomobryidae")


test_y = 'CTATATTTAATCTTTGGTGCATGAGCAGGAATAGTGGGCACAGCCCTTAGCCTACTTATTCGTACAGAATTAAGCCAACCCGGGACACTTCTGGGGGATGATCAAATCTACAATGTTATTGTAACTGCTCACGCTTTTGTAATAATCTTTTTTATAGTTATACCCGTAATAATCGGCGGTTTCGGAAATTGATTAGTGCCTTTAATAATTGGTGCACCAGACATAGCTTTTCCTCGAATAAATAACATAAGTTTTTGACTATTGCCACCATCTCTTCTATTACTTTTAGCTTCTGCTGGCGTCGAAGCAGGGGCTGGAACCGGATGAACGGTCTACCCCCCTCTTGCAGGTAATATAGCCCATGCTGGCGCATCCGTGGATTTAGCCATCTTCTCACTCCATTTAGCCGGTATTTCCTCCATTTTAGCCTCTATTAACTTTATTACTACTATTATTAATATAAAACCGCCTGCAATTTCTCAATACCAAACCCCACTCTTTGTCTGATCCATCCTTGTAACCACTGTCCTTCTTCTACTTGCTCTCCCCGTCCTTGCCGCTGCAATTACAATACTCTTAACTGACCGTAATTTAAATACAACATTTTTTGACCCAGCGGGAGGAGGGGACCCCATTCTTTACCAACACTTA'

test_z = 'LYLIFGAWAGMVGTALSLLIRTELSQPGTLLGDDQIYNVIVTAHAFVMIFFMVMPVMIGGFGNWLVPLMIGAPDMAFPRMNNMSFWLLPPSLLLLLASAGVEAGAGTGWTVYPPLAGNMAHAGASVDLAIFSLHLAGISSILASINFITTIINMKPPAISQYQTPLFVWSILVTTVLLLLALPVLAAAITMLLTDRNLNTTFFDPAGGGDPILYQHLF'

nchar(test_y)
nchar(test_z)*3
translate_DNA(test_y)



y3 = 'ATTTTTGGTGCATGAGCAGGAATAATTGGAACAGCCCTAAGTCTTTTAATTCGAGCTGAACTTGGACAACCAGGCTCTCTTTTAGGAGATGATCAGATTTATAATGTAATTGTAACTGCCCACGCTTTCGTAATAATCTTTTTCATAGTTATACCAATTATAATTGGTGGTTTTGGGAATTGGCTCGTGCCTTTAATAATTGGTGCGCCAGATATGGCCTTCCCACGAATAAACAACATAAGCTTTTGGCTTCTTCCACCATCATTCCTTCTCCTCTTAGCTTCCGCTGGGGTAGAAGCTGGAGCAGGTACTGGCTGAACAGTTTACCCTCCATTAGCTAGCAACTTAGCTCATGCTGGACCATCTGTTGACCTAGCTATCTTTTCCCTACACCTAGCCGGTGTATCATCAATCTTAGCCTCAATTAATTTCATTACAACTATTATTAACATGAAACCTCCAGCCATCTCTCAATATCAAACACCATTATTTGTTTGATCCATTCTTGTAACTACTATCCTACTTCTCCTCTCACTTCCAGTTCTCGCAGCAGGAATTACAATATTACTCACAGATCGTAACCTTAATACTACATTCTTTGATCCTGCAGGGGGAGGAGATCCAATCCTTTATCAACACTTATTCTGATTCTTC'
z3 = 'FPIFGAWAGMIGTALSLLIRAELGQPGSLLGDDQIYNVIVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGAPDMAFPRMNNMSFWLLPPSFLLLLASAGVEAGAGTGWTVYPPLASNLAHAGPSVDLAIFSLHLAGVSSILASINFITTIINMKPPAISQYQTPLFVWSILVTTILLLLSLPVLAAGITMLLTDRNLNTTFFDPAGGGDPILYQHLFWFFATFPSGALRLKRPPQPPHLPLX'

nchar(y3)
nchar(z3)*3
translate_DNA(y3) #the aminoraw has two extra amino acids on the front and several others on the back.



test_a = "ttatattttatttttgggaatttgagcagggatagtaggaactttctctaagattattaattcgagcagaattaggtcatcctggatctttaattgggatgatcaaatttataacactattgtaacagctcatgcttttattataattttttttatagttatacctattataattggggatttggaaattgattagtacctttaatattaggagctcctgatatagctttcccccgtataaataatataagtttttgattattacctccttctttaactttattaatttctagaagaattgtagaaaatggtgtaggaactggatgaacagtttacccccctctttcttcaaatattgctcatggaggaagttcagtagatttagctattttttctcttcatttagcgggaattt"
censored_translation(test_a)

test_b = "---------------ttatattttatttttggg atttgagcagggatagtaggaactt ctctaagattattaattcgagcagaattaggtcatcctggatctttaattgg-gatgatcaaatttataacactattgtaacagctcatgcttttattataattttttttatagttatacctattataattgg-ggatttggaaattgattagtacctttaatattaggagctcctgatatagctttcccccgtataaataatataagtttttgattattacctccttctttaactttattaatttctagaagaattgtagaaaatggtgtaggaactggatgaacagtttacccccctctttcttcaaatattgctcatggaggaagttcagtagatttagctattttttctcttcatttagcgggaattt-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
censored_translation(test_b)

