seq_Ns = 'cttcacttgatttttggtgcaNNNNNNNgaatagtaggaactgctttaagtctccttattcgagcagaactgggtcaacctggttcacttttaggtgatgaccagatctacaatgtgatcgtaaccgcccatgctttagtaataattttttttatagttataccggtaataattggtggctttggaaactgactagtgcccctaataattggtgcaccagatatggcctttcctcgaataaataacataagtttttgactccttccaccatcattccttttattattagcttctgcaggggtagaagccggagctggcaccggctgaacagtttacccacccttatcgggtaatttagcacatgccgggccatctgttgatttaactattttttcacttcatttagcaggtgtatcatcaattttagcctcaattaattttatcacaactattattaatataaaaccaccagctatttctcaataccaaacaccattatttgtttgatccgttcttgtaactactattttactacttttagcccttccagtacttgcagctggaattacaatattattaacagatcgaaacctaaataccacattctttgaccctgctggtggaggagatcctatccactatcaacatcta'


test_Ns = coi5p(seq_Ns)
test_Ns
test_Ns = frame(test_Ns)
test_Ns
test_Ns = translate(test_Ns)
test_Ns
test_Ns = translate(test_Ns, trans_table = 5)
test_Ns
test_Ns = indel_check(test_Ns)
test_Ns
names(test_Ns)
