


test_that("A long sequence is framed and translated properly", {

  sequence = 'aaccgctgattattttcaaccaaccacaaagatatcggcaacattatacattctttttagaatttgggcaggccttcttggaagaagcttaagtcttataatccgtattgagctaaggcaaccaaaagaaattttaattaatagtttaatatataacacaattgtaacagcccatgcaattgtaataattttttttactgttataccttttttaattggaggacttggtaattgactaattcctttattcttacatttgccagacatagcttttcctcgcttaaataatgttagtttttggcttctccctccttccttaatattgtttttaataagactatttagagggagaggagctggtacaggttggacgatatacccccctctctctaatagcctttataggcctagtataagggtagacatagttattttatctttacatttagcggggacatcctctttattaggagctttaaattttagagttactattttaacttgttctttttttaaaaagggattaaatagtatgccagtttttatttgagcgttacttgtaacttctttcttgttacatttatctgtaccagtccttgcaggagctttaacaatgctattattggaccgtaattttaatacaactttttttgatccttcaggagggggggaccctgtcctgtatcagcattta'
  sequence_framed = '-cattatacattctttttagaatttgggcaggccttcttggaagaagcttaagtcttataatccgtattgagctaaggcaaccaaaagaaattttaattaatagtttaatatataacacaattgtaacagcccatgcaattgtaataattttttttactgttataccttttttaattggaggacttggtaattgactaattcctttattcttacatttgccagacatagcttttcctcgcttaaataatgttagtttttggcttctccctccttccttaatattgtttttaataagactatttagagggagaggagctggtacaggttggacgatatacccccctctctctaatagcctttataggcctagtataagggtagacatagttattttatctttacatttagcggggacatcctctttattaggagctttaaattttagagttactattttaacttgttctttttttaaaaagggattaaatagtatgccagtttttatttgagcgttacttgtaacttctttcttgttacatttatctgtaccagtccttgcaggagctttaacaatgctattattggaccgtaattttaatacaactttttttgatccttcaggagggggggaccctgtcctgtatcagcattta'

  sequence_AAcensored = "-LYILF?IWAGLLG?SLSL?IRIEL?QP?EILINSL?YNTIVTAHAIV?IFFTV?PFLIGGLGNWLIPLFLHLPD?AFPRLNNVSFWLLPPSL?LFL??LF?G?GAGTGWT?YPPLSNSLY?PS??VD?VILSLHLAGTSSLLGALNF?VTILTCSFF?KGLNSMPVFIWALLVTSFLLHLSVPVLAGALTMLLLDRNFNTTFFDPSGGGDPVLYQHL"
  sequence_AA5 = "-LYILFSIWAGLLGSSLSLMIRIELSQPKEILINSLMYNTIVTAHAIVMIFFTVMPFLIGGLGNWLIPLFLHLPDMAFPRLNNVSFWLLPPSLMLFLMSLFSGSGAGTGWTMYPPLSNSLYSPSMSVDMVILSLHLAGTSSLLGALNFSVTILTCSFFKKGLNSMPVFIWALLVTSFLLHLSVPVLAGALTMLLLDRNFNTTFFDPSGGGDPVLYQHL"

  dat = coi5p(sequence )
  expect_equal(dat$raw, sequence)
  expect_identical(dat$name, character(0))

  dat = frame(dat)
  expect_equal(dat$framed, sequence_framed)

  dat = translate(dat)
  expect_equal(dat$aaSeq, sequence_AAcensored)

  dat = indel_check(dat)
  expect_equal(dat$indel_likely, FALSE)
  expect_equal(dat$stop_codons, FALSE)

  dat = translate(dat, trans_table = 5)
  expect_equal(dat$aaSeq, sequence_AA5)

  dat = indel_check(dat)
  expect_equal(dat$indel_likely, FALSE)
  expect_equal(dat$stop_codons, FALSE)

})
